name: DynamicViewDistance
main: net.gamesketch.viewdistance.DynamicViewDistance
version: 0.0.1
website: http://www.gamesketch.net
author: Cogito
description: >
             Set the view distance on a server-wide, per-world and per-player basis.
             Allows setting variable view distance based on server load.
commands:
  setview:
    description: Set the view distance.
    usage: |
           /<command> [server|world <name>|player <name>] distance
           Example: /<command> server 7 - set the server view distance to 7.
           Example: /<command> world hell 3 - set the "hell" world's view distance to 3.
           Example: /<command> player admin 15 - set the "admin" player's view distance to 15.
  resetview:
    description: Reset the view distance to defaults.
    usage: |
           /<command> [server|world <name>|player <name>] distance
           Example: /<command> server - reset the server view distance to 5.
           Example: /<command> world hell - reset the "hell" world's view distance to the server's.
           Example: /<command> player admin - reset the "admin" player's view distance to the world's.
permissions:
  viewdistance:
    default: op
    description: allow full control over view distances
    children:
      viewdistance.set: true
      viewdistance.reset: true

  viewdistance.set:
    description: |
                 allow the setting of all view distances
                 can use world.worldname and player.playername for fine grained control
    children:
      viewdistance.set.server: true
      viewdistance.set.world: true
      viewdistance.set.player: true
  viewdistance.set.server:
    description: allow setting of the server view distance
  viewdistance.set.world:
    description: allow setting of all world view distances
  viewdistance.set.player:
    description: allow setting of all player view distances

  viewdistance.reset:
    description: |
                 allow the resetting of all view distances
                 can use world.worldname and player.playername for fine grained control
    children:
      viewdistance.reset.server: true
      viewdistance.reset.world: true
      viewdistance.reset.player: true
  viewdistance.reset.server:
    description: allow resetting of the server view distance
  viewdistance.reset.world:
    description: allow resetting of all world view distances
  viewdistance.reset.player:
    description: allow resetting of all player view distances